services:

  postgres:
    image: postgres:15-alpine
    container_name: dev_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dev-db/init:/docker-entrypoint-initdb.d
    networks:
      - backend-net

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: dev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - backend-net

  glassfish:
    build:
      context: ./glassfish-build
      dockerfile: Dockerfile
    image: custom-glassfish:1.0
    container_name: dev_glassfish
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:4848:4848"
    environment:
      - JVM_ARGS=-Xms512m -Xmx1024m
    volumes:
      - ./java/deployments:/opt/glassfish7/glassfish/domains/domain1/autodeploy

    depends_on:
      - postgres
    networks:
      - backend-net
  
  nginx:
    image: nginx:alpine
    container_name: dev_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - glassfish
    networks:
      - backend-net


volumes:
  pgdata:

networks:
  backend-net:
















