

services:
  glassfish:
    image: ghcr.io/eclipse-ee4j/glassfish:7.0.23@sha256:4c9941c99201a489992ce88196250ea8056b3bd998b589b822e05dd8fb759eae
    container_name: dev_glassfish
    ports:
      - "8080:8080"   # Application
      - "4848:4848"   # Admin Console
    environment:
      - JVM_ARGS=-Xms512m -Xmx1024m
    volumes:
      - ./deployments:/glassfish/domains/domain1/autodeploy
    depends_on:
      - postgres
    networks:
      - backend-net



